### ISSUE TITLE
в фф и в ие11 плеер отличается по стилю

### ISSUE THREAD

**Issue by VladyslavKovalchuk** [MalahVitalij/rocket-konkovo#38]
http://prntscr.com/llktvn
http://prntscr.com/llkuci

**Comment by VladyslavKovalchuk** [comment]
с ие11 понятно, прочитал в другой правке. Можно ли подправить в фф?

**Comment by LastQuinsy** [comment]
Не получилась поменять цвет дорожки в FF. Я поставил всем браузерам цвет как в FF. Теперь они везде одинаковые (кроме IE - там у плеера другой вид)
